### ISSUE TITLE
Source type is empty

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-browser-extension#173]
At first I didn't see any menu icons. All I saw was just the black background. After that I removed Buttercup from firefox, cleared the Cache and Cookies, restarted Firefox, installed Buttercup and tried it again. Now I see nothing:

![bildschirmfoto 2018-09-21 um 18 37 53](https://user-images.githubusercontent.com/25926588/45894139-d425ea00-bdcd-11e8-85ea-e11db7a124c7.png)

![bildschirmfoto 2018-09-21 um 18 40 18](https://user-images.githubusercontent.com/25926588/45894153-dbe58e80-bdcd-11e8-9061-e587eec3bb35.png)

System Info:
Browser: Firefox 62.0 (64 Bit)
System: MacOS 10.13.6
Webconsole:
````
Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered. components.manifest:163
Laden fehlgeschlagen für das <script> mit der Quelle "moz-extension://30cf1a2e-cfdb-a749-a913-b18b3db4c0ad/background-buttercup.js". _generated_background_page.html:5
Laden fehlgeschlagen für das <script> mit der Quelle "moz-extension://30cf1a2e-cfdb-a749-a913-b18b3db4c0ad/background-vendor.js". _generated_background_page.html:6
Laden fehlgeschlagen für das <script> mit der Quelle "moz-extension://30cf1a2e-cfdb-a749-a913-b18b3db4c0ad/background-index.js". _generated_background_page.html:7
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIWebNavigation.loadURIWithOptions] browser-child.js:352
Use of nsIFile in content process is deprecated. NetUtil.jsm:266:12
NS_ERROR_NOT_AVAILABLE: Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIWebNavigation.loadURIWithOptions] browser-child.js:352 
````

**Comment by perry-mitchell** [comment]
Hi @julianpoemp - I just updated:

![image](https://user-images.githubusercontent.com/3869469/45931669-daf16000-bf79-11e8-917a-824ee31d05f9.png)

Can't see any issue here.. Any chance you can inspect the background script for any init errors?

**Comment by julianpoemp** [comment]
@perry-mitchell Did you restart Firefox after the update?

I did the update on another account, too. First it works, but then I had to restart Firefox. After that it doesn't work again. Now, I see the black background:

![bildschirmfoto 2018-09-24 um 13 09 57](https://user-images.githubusercontent.com/25926588/45949230-88f11e80-bffb-11e8-8b11-657b3595fa84.png)

Every time I open the popup the following error occurs:

![bildschirmfoto 2018-09-24 um 13 15 30](https://user-images.githubusercontent.com/25926588/45949360-f00ed300-bffb-11e8-8730-a0f44866229c.png)

Here the full log:
````Could not map contract ID '@mozilla.org/fxaccounts/push;1' to CID {1b7db999-2ecd-4abf-bb95-a726896798ca} because no implementation of the CID is registered. components.manifest:163
Successfully compiled asm.js code (total compilation time 1ms; not stored in cache (too small to benefit)) adblockplus.js
[info] (Migration) Beginning data migration for new storage background-index.js:1:32482
[info] Starting... background-index.js:1:32482
[info] Detected browser: firefox background-index.js:1:32482
[info] Started successfully background-index.js:1:32482
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: call to eval() or related function blocked by CSP. background-index.js:1
[info] (Migration) Migrating 0 keys background-index.js:1:32482
[info] (Migration) Removing original items background-index.js:1:32482
[info] (Migration) Migration complete background-index.js:1:32482
[info] Rehydrated archive manager background-index.js:1:32482
[info] Sending state update to 0 ports 
Object { type: "archives/set", payload: (2) […], actionSync: 0 }
background-index.js:1:32482
[info] Port connected: buttercup-state background-index.js:1:32482
[info] Sent full state to new port 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
background-index.js:1:32482
[info] Port disconnected: buttercup-state background-index.js:1:32482
Use of nsIFile in content process is deprecated.
NetUtil.jsm:266:12
[info] Port connected: buttercup-state background-index.js:1:32482
[info] Sent full state to new port 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
background-index.js:1:32482
Die Zeichenkodierung des HTML-Dokuments wurde nicht deklariert. Das Dokument wird in manchen Browser-Konfigurationen mit verstümmeltem Text dargestellt, wenn das Dokument Zeichen außerhalb des US-ASCII-Bereichs enthält. Die Zeichenkodierung der Seite muss im Dokument oder Transferprotokoll deklariert werden. popup.html
[info] Received full state update from background 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
popup.js:1:563244
Error: "No image asset for archive type: "
valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576628valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576534valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576098valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:575931Lgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:425786Sgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:430666yhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440206zhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440501Whmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443995Zhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443516Xhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443351Bhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:442735pgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:441980enqueueSetStatemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:417576setStatemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:358493onStateChangemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:176636dispatchmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:180650createSyncMiddlewaremoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:526254amoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515444createThunkMiddlewaremoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515962handleBackgroundMessagemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:103185 popup.js:1:435048
[Mitteilungsdetails anzeigen/ausblenden] No image asset for archive type: popup.js:1
[info] Port disconnected: buttercup-state background-index.js:1:32482
[info] Port connected: buttercup-state background-index.js:1:32482
[info] Sent full state to new port 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
background-index.js:1:32482
Die Zeichenkodierung des HTML-Dokuments wurde nicht deklariert. Das Dokument wird in manchen Browser-Konfigurationen mit verstümmeltem Text dargestellt, wenn das Dokument Zeichen außerhalb des US-ASCII-Bereichs enthält. Die Zeichenkodierung der Seite muss im Dokument oder Transferprotokoll deklariert werden. popup.html
[info] Received full state update from background 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
popup.js:1:563244
Error: "No image asset for archive type: "
valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576628valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576534valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576098valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:575931Lgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:425786Sgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:430666yhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440206zhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440501Whmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443995Zhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443516Xhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443351Bhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:442735pgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:441980enqueueSetStatemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:417576setStatemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:358493onStateChangemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:176636dispatchmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:180650createSyncMiddlewaremoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:526254amoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515444createThunkMiddlewaremoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515962handleBackgroundMessagemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:103185 popup.js:1:435048
[Mitteilungsdetails anzeigen/ausblenden] No image asset for archive type: popup.js:1
[info] Port disconnected: buttercup-state background-index.js:1:32482
Die Zeichenkodierung des HTML-Dokuments wurde nicht deklariert. Das Dokument wird in manchen Browser-Konfigurationen mit verstümmeltem Text dargestellt, wenn das Dokument Zeichen außerhalb des US-ASCII-Bereichs enthält. Die Zeichenkodierung der Seite muss im Dokument oder Transferprotokoll deklariert werden. popup.html
[info] Port connected: buttercup-state background-index.js:1:32482
[info] Sent full state to new port 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
background-index.js:1:32482
[info] Received full state update from background 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
popup.js:1:563244
Error: "No image asset for archive type: "
valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576628valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576534valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576098valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:575931Lgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:425786Sgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:430666yhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440206zhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440501Whmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443995Zhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443516Xhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443351Bhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:442735pgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:441980enqueueSetStatemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:417576setStatemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:358493onStateChangemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:176636dispatchmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:180650createSyncMiddlewaremoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:526254amoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515444createThunkMiddlewaremoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515962handleBackgroundMessagemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:103185 popup.js:1:435048
[Mitteilungsdetails anzeigen/ausblenden] No image asset for archive type: popup.js:1
[info] Port disconnected: buttercup-state background-index.js:1:32482
[info] Port connected: buttercup-state background-index.js:1:32482
[info] Sent full state to new port 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
background-index.js:1:32482
[info] Sending state update to 1 ports 
Object { type: "searching/results/set", payload: [], actionSync: 1 }
background-index.js:1:32482
[info] Sending state update to 1 ports 
Object { type: "searching/setSources", payload: 0, actionSync: 2 }
background-index.js:1:32482
[info] Port disconnected: buttercup-state background-index.js:1:32482
[info] Saved login credentials from tab: 4 background-index.js:1:32482
[info] Port connected: buttercup-state background-index.js:1:32482
[info] Sent full state to new port 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
background-index.js:1:32482
[info] Port disconnected: buttercup-state background-index.js:1:32482
[info] Port connected: buttercup-state background-index.js:1:32482
[info] Sent full state to new port 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
background-index.js:1:32482
[info] Port disconnected: buttercup-state background-index.js:1:32482
[info] Port connected: buttercup-state background-index.js:1:32482
[info] Sent full state to new port 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
background-index.js:1:32482
Die Zeichenkodierung des HTML-Dokuments wurde nicht deklariert. Das Dokument wird in manchen Browser-Konfigurationen mit verstümmeltem Text dargestellt, wenn das Dokument Zeichen außerhalb des US-ASCII-Bereichs enthält. Die Zeichenkodierung der Seite muss im Dokument oder Transferprotokoll deklariert werden. popup.html
[info] Received full state update from background 
Object { app: {…}, archives: {…}, dropbox: {…}, searching: {…} }
popup.js:1:563244
Error: "No image asset for archive type: "
valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576628valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576534valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576098valuemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:575931Lgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:425786Sgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:430666yhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440206zhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440501Whmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443995Zhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443516Xhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443351Bhmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:442735pgmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:441980enqueueSetStatemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:417576setStatemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:358493onStateChangemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:176636dispatchmoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:180650createSyncMiddlewaremoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:526254amoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515444createThunkMiddlewaremoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515962handleBackgroundMessagemoz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:103185 popup.js:1:435048
Yg
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:435048
fh/c.callback
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:437885
Wf
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:415959
Xf
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:416422
bi
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:447880
Wh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:444008
Zh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443516
Xh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443351
Bh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:442735
pg
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:441980
enqueueSetState
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:417576
F.prototype.setState
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:358493
__webpack_exports__.a/</Connect</Connect.prototype.onStateChange
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:176636
dispatch
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:180650
exports.createSyncMiddleware/</</<
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:526254
__webpack_exports__.a/</</<
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515444
createThunkMiddleware/</</<
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515962
handleBackgroundMessage
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:103185
[Mitteilungsdetails anzeigen/ausblenden] No image asset for archive type: popup.js:1
value/</<
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576628
value/<
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576534
map self-hosted:292:17 value
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:576098
value
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:575931
Lg
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:425786
Sg
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:430666
yh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440206
zh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:440501
Wh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443995
Zh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443516
Xh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:443351
Bh
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:442735
pg
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:441980
enqueueSetState
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:417576
F.prototype.setState
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:358493
__webpack_exports__.a/</Connect</Connect.prototype.onStateChange
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:176636
<anonym> self-hosted:984:17 dispatch
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:180650
exports.createSyncMiddleware/</</<
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:526254
__webpack_exports__.a/</</<
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515444
createThunkMiddleware/</</<
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:515962
handleBackgroundMessage
moz-extension://a13d2b22-3fc8-3e45-aac7-991edd04bc3d/popup.js:1:103185
apply self-hosted:4553:5 applySafeWithoutClone
resource://gre/modules/ExtensionCommon.jsm:234:16
addListener/asyncWithoutClone/<
resource://gre/modules/ExtensionCommon.jsm:1932:20
````

**Comment by perry-mitchell** [comment]
Hmm.. Very weird error. Sounds like there's some corrupted/incorrect archive type specified.. Are you able to open up the state message in your screenshot like this?

![image](https://user-images.githubusercontent.com/3869469/45958348-e7c88f00-c01f-11e8-847f-ba0a7c1da2da.png)

No need to send the screenshot, but it'd be good to make sure your archive types are sane ("dropbox", "webdav" etc.).

Have you experimented with this build at all? Is it development or from the store?

**Comment by julianpoemp** [comment]
no, "type" is "":
````
colour: "#000000"
​​​​id: "bbe052ae-b608-4a52-948c-8b1463b78277"
​​​​name: "Julian"
​​​​order: 0
​​​​state: "locked"
​​​​status: "locked"
​title: "My Owncloud"
​type: ""
````

> Have you experimented with this build at all?

No

> Is it development or from the store?

It's from the store. The crazy thing is, that sometimes it works, sometimes not. On the other account on my PC I reinstalled the addon. Now, there are no archives and it works nomally. I think this error occurs only after adding archives. Without archives it seems to work...

**Comment by julianpoemp** [comment]
I debugged the extension and ran `browser.storage.local.clear()`. Don't know how to reload the extension, that's why I restarted Firefox. After that I added one archive. It works as long as I havn't restarted Firefox.
I have the same problem on WIndows.

**Comment by julianpoemp** [comment]
Update: The Buttercup extension is invisible as long as the archive is locked. If I unlock the archive in the tab opened automatically I see all items in the popup.

**Comment by morojgovany** [comment]
On linux debian 9 same thing is happening, the app is freezing when opening the browser after added a new archive type webdav in the last session, in the console the archive type is blank.
I tested it on chrome, firefox developper edition and vivaldi, all had the same behavior. I noticed the problem appeared after an update of my first webdav server, so I tested it on one of mine but no changes.

**Comment by perry-mitchell** [comment]
Ok, so the incident definitely doesn't seem to be an isolated one. I however have not yet been able to reproduce the issue.. We need some way to do that, unless someone can contribute a PR. Unsure of whether this is related to a source (webdav, etc.) or some other combination of factors.

**Comment by morojgovany** [comment]
Here is my complete webdav server conf if it could help :
nginx version: nginx/1.6.2

```
server {  
    listen 443 ssl;
    server_name example.com;
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;
    ssl_dhparam /etc/letsencrypt/live/example.com/dhparam.pem;
    server_tokens off;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 5m;
    ssl_stapling on;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    add_header X-Content-Type-Options "nosniff";
    add_header X-Xss-Protection "1; mode=block";
    add_header 'Referrer-Policy' 'no-referrer';
    add_header Content-Security-Policy "default-src 'self' example.com; frame-src 'self' giphy.com ; img-src 'self' giphy.com secure.gravatar.com data:; font-src 'self' data:; script-src 'self' example.com; style-src 'self' 'unsafe-inline';";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
    proxy_cookie_path / /;
    more_set_headers "Set-Cookie: $sent_http_set_cookie; secure; HttpOnly";
    
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";

    ## Start: Timeouts ##
    client_body_timeout   10;
    client_header_timeout 10;
    keepalive_timeout     5 5;
    send_timeout          10;
    ## End: Timeouts ##

    ## Start: Size Limits & Buffer Overflows ##
    client_body_buffer_size  1K;
    client_header_buffer_size 1k;
    client_max_body_size 40m;
    large_client_header_buffers 2 1k;
    ## END: Size Limits & Buffer Overflows ##

    # gogs conf
    location / {
        proxy_pass https://127.0.0.1:3000;
	rewrite                 ^/(.*) /$1 break;
        rewrite                 ^/$ /$1 break;
    }

    location /dav {
        alias /path/dav;
        client_body_temp_path   /path/tmp;
        dav_methods             PUT DELETE MKCOL COPY MOVE;
        dav_ext_methods         PROPFIND OPTIONS;
        create_full_put_path    on;
        dav_access              user:rw group:rw;
        autoindex               on;
        auth_basic "restricted";
        auth_basic_user_file /path/passwd;
        proxy_connect_timeout  500s;
        proxy_read_timeout  500s;
        proxy_send_timeout  500s;
        send_timeout  500s;
     }

    ## keybase conf
    location /keybase.txt {
        root /proof;
    }
}

# Redirect HTTP requests to HTTPS
server {  
    listen 80;
    server_name example.com;
    server_tokens off;
    # Bad Bot Blocker
    include /etc/nginx/bots.d/ddos.conf; 
    include /etc/nginx/bots.d/blockbots.conf;

    ## Start: Size Limits & Buffer Overflows ##
    client_body_buffer_size  1K;
    client_header_buffer_size 1k;
    client_max_body_size 1k;
    large_client_header_buffers 2 1k;
    ## END: Size Limits & Buffer Overflows ##
    
    ## Start: Timeouts ##
    client_body_timeout   10;
    client_header_timeout 10;
    keepalive_timeout     5 5;
    send_timeout          10;
    ## End: Timeouts ##

    return 301 https://$host$request_uri;
}
```  
I can reproduce it on a synology NAS with native webdav too, on windows 10 and firefox browser.
If i have enouth time, I will test and provide you a docker image or another solution to reproduce it.
Best regards

**Comment by julianpoemp** [comment]
Perhaps this has something to do with a new change in the Firefox Addon API. Or this is a bug in Firefox and solved in a later version.

**Comment by morojgovany** [comment]
> Perhaps this has something to do with a new change in the Firefox Addon API. Or this is a bug in Firefox and solved in a later version.

It was my second thought (after a misconfiguration of my webdav) but it's the same behavior with vivaldi (my everyday browser), chrome and FF so it can't be due only from that.

**Comment by morojgovany** [comment]
I discovered that bug is reproducible only with a fresh install of the last version of buttercup, you need to add a first new archive and reboot the browser. I had an "old" version on an other computer and I can't reproduce the bug till I updated the browser and it's extensions.

**Comment by perry-mitchell** [comment]
Thanks @morojgovany - I'm still not able to see the issue myself, but I have an idea where _part_ of the issue is. The function that's throwing the error is expecting a type for the icon, which is rather pointless when it comes to breaking the whole extension.

I'll be releasing an update for WebDAV fixes soon, and this patch may find its way in. Let's home it at least brings the extension back online in terms of usability. We'll still have to try and figure out where this particular problem is coming from.

**Comment by perry-mitchell** [comment]
> Perhaps this has something to do with a new change in the Firefox Addon API. Or this is a bug in Firefox and solved in a later version.

@julianpoemp Hmm, I don't see them introducing any breaking changes, and the only area I can think that might be affected is the storage. `type`, when a vault is locked, comes from the browser storage. All the locked vault details are also stored there, so I can't see one breaking without the other.

I wonder if this is some kind of race condition..

**Comment by perry-mitchell** [comment]
Scratch that.. even after forcibly killing the type field, I wasn't able to reproduce in Firefox:

![image](https://user-images.githubusercontent.com/3869469/46584434-be6e2100-ca6b-11e8-98b0-d4dab34ab92e.png)

**Comment by morojgovany** [comment]
I still can't understand why this behavior is not reproducible, I tried another webdav and the bug still exists for me... Your fix made this not blocking anymore, but it is weird.
I opened a testing instance on my server, the config is exactly the same as mine. I provide you the credentials in private if possible.

**Comment by perry-mitchell** [comment]
@morojgovany It is weird I agree. I can't understand why the type wouldn't be set. The order of actions is as follows:

1. Connect to service
2. Select archive
3. Enter name & password
4. Fetch and add archive (locked) (at this stage, type should be added manually to the state)
5. Unlock archive (unlocked) (type should now be updated from the unlocked archive's state, and should be identical)

The 2 last steps should always ensure that the type is not empty. I haven't yet been able to find a situation, while unlocking or adding, that the type is empty. I'm not sure that testing with other people's accounts will help, but I'm definitely willing to try.

I would recommend creating me a temporary account (don't give me access to yours, please), confirming that the bug still occurs with such an account for you, and then send me those details via Keybase.io if possible. I'm [perrymitchell](https://keybase.io/perrymitchell) there.

**Comment by bless-9** [comment]
I had the exact same issue, for all browsers as well, for a couple of weeks. But 1.12.0 finally fixed for me.

**Comment by julianpoemp** [comment]
@bless-9 yes, it works on my PC with Firefox and 1.12.0, too.

**Comment by perry-mitchell** [comment]
Good to hear 1.12 has bypassed the breaking issue, but I guess you’re still seeing empty types in the UI?

The issue remains in that there aren’t types set for some reason :(

**Comment by perry-mitchell** [comment]
I was able to reproduce this finally.. If for some reason the source is actually managed to be loaded without a type, it won't be updated with a type in the storage later. I'll be releasing a patch soon.

**Comment by perry-mitchell** [comment]
Released in 1.12.1
